project:
  type: website
  output-dir: docs

website:
  title: "Sri Lanka Dengue Atlas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - spatial.qmd
      - time.qmd
      - seasonal.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    number-sections: true
    fig-caption: true
    toc: true

editor: visual

